[package]
name = "mc-ledger-types"
version = "1.1.0"
authors = ["MobileCoin"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
# mobilecoin
mc-attest-core = { path = "../../attest/core", default-features = false }
mc-transaction-core = { path = "../../transaction/core" }
mc-watcher-api = { path = "../../watcher/api" }

# third-party
displaydoc = { version = "0.2", default-features = false }
prost = { version = "0.8", default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
